### For the opensource Datasets taken from the following website:
https://www.maths.lth.se/matematiklth/personal/calle/dataset/dataset.html

You can use the following code to find out the K matrix (camera params) from data.mat file of the dataset.

K = [   [Fx, Cx, 0],
        [0,  Fy, Cy],
        [0,  0,  1]]

        

In [2]:
import numpy as np
import scipy.io
from scipy.linalg import rq

# Load the data from the .mat file
data = scipy.io.loadmat('data.mat')

# Choose a camera (e.g., the first one)
P1 = data['P'][0][0]
# Extract the left 3x3 matrix from the projection matrix
M = P1[:, :3]

# Perform RQ decomposition (QR decomposition of the flipped M)
K, R=rq(M)

K=K/K[2,2]

print(K)

[[-2.39395217e+03  4.90274488e-13  9.32382177e+02]
 [-0.00000000e+00  2.39811854e+03  6.28264995e+02]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00]]
